name: Deploy to Koyeb

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
      - name: Install Koyeb-CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}