name: Deploy to Koyeb

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-22.04
    steps:
      - name: Install Koyeb-CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Build and deploy the application
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: spring-boot-${{ github.ref_name }}
          service-ports: "8080:http"
          service-routes: "/:8080"
          skip-cache: true
          instance-type: micro