name: Deploy to Koyeb

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-22.04
    steps:
      - name: login
        uses: koyeb/cli:latest
        run: koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
      - name: deploy
        uses: koyeb/cli:latest
        run: koyeb service deploy --app ${{ secrets.KOYEB_APP_NAME }} --service ${{ secrets.KOYEB_SERVICE_NAME }} --artifact=target/*.jar